name: StitchWell
channels:
  - conda-forge
  - defaults
dependencies:
  - appdirs=1.4.4=pyh9f0ad1d_0
  - appnope=0.1.2=py39h6e9494a_1
  - argon2-cffi=20.1.0=py39h89e85a6_2
  - async_generator=1.10=py_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bleach=3.3.1=pyhd8ed1ab_0
  - blosc=1.21.0=he49afe7_0
  - brotli=1.0.9=h0d85af4_5
  - brotli-bin=1.0.9=h0d85af4_5
  - brotlipy=0.7.0=py39h89e85a6_1001
  - brunsli=0.1=h046ec9c_0
  - bzip2=1.0.8=h0d85af4_4
  - c-ares=1.17.1=h0d85af4_1
  - ca-certificates=2021.5.30=h033912b_0
  - cairo=1.16.0=he43a7df_1008
  - certifi=2021.5.30=py39h6e9494a_0
  - cffi=1.14.6=py39hb71fe58_0
  - cfitsio=3.470=h01dc385_7
  - chardet=4.0.0=py39h6e9494a_1
  - charls=2.2.0=h046ec9c_0
  - charset-normalizer=2.0.0=pyhd8ed1ab_0
  - cloudpickle=1.6.0=py_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cryptography=3.4.7=py39ha2c9959_0
  - cycler=0.10.0=py_2
  - cytoolz=0.11.0=py39h89e85a6_3
  - dask-core=2021.7.2=pyhd8ed1ab_0
  - dbus=1.13.6=ha13b53f_2
  - debugpy=1.4.1=py39h9fcab8e_0
  - decorator=5.0.9=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - expat=2.4.1=he49afe7_0
  - ffmpeg=4.3.2=h4dad6da_0
  - fontconfig=2.13.1=h10f422b_1005
  - freetype=2.10.4=h4cff582_1
  - fsspec=2021.7.0=pyhd8ed1ab_0
  - gettext=0.19.8.1=h7937167_1005
  - giflib=5.2.1=hbcb3906_2
  - glib=2.68.3=he49afe7_0
  - glib-tools=2.68.3=he49afe7_0
  - gmp=6.2.1=h2e338ed_0
  - gnutls=3.6.13=h756fd2b_1
  - graphite2=1.3.13=h2e338ed_1001
  - harfbuzz=2.8.2=h159f659_0
  - hdf5=1.10.6=nompi_hc5d9132_1114
  - icu=68.1=h74dc148_0
  - idna=3.1=pyhd3deb0d_0
  - imagecodecs=2021.7.30=py39he5b32f2_0
  - imageio=2.9.0=py_0
  - importlib-metadata=4.6.3=py39h6e9494a_0
  - ipykernel=6.0.3=py39h71a6800_0
  - ipython=7.26.0=py39h71a6800_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.3=pyhd3deb0d_0
  - jasper=1.900.1=h636a363_1006
  - jedi=0.18.0=py39h6e9494a_2
  - jinja2=3.0.1=pyhd8ed1ab_0
  - jpeg=9d=hbcb3906_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter=1.0.0=py39h6e9494a_6
  - jupyter_client=6.1.12=pyhd8ed1ab_0
  - jupyter_console=6.4.0=pyhd8ed1ab_0
  - jupyter_core=4.7.1=py39h6e9494a_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_widgets=1.0.0=pyhd8ed1ab_1
  - jxrlib=1.1=h35c211d_2
  - kiwisolver=1.3.1=py39hf018cea_1
  - krb5=1.19.2=hcfbf3a7_0
  - lame=3.100=h35c211d_1001
  - lcms2=2.12=h577c468_0
  - lerc=2.2.1=h046ec9c_0
  - libaec=1.0.5=he49afe7_0
  - libblas=3.9.0=10_openblas
  - libbrotlicommon=1.0.9=h0d85af4_5
  - libbrotlidec=1.0.9=h0d85af4_5
  - libbrotlienc=1.0.9=h0d85af4_5
  - libcblas=3.9.0=10_openblas
  - libclang=11.1.0=default_he082bbe_1
  - libcurl=7.78.0=hf45b732_0
  - libcxx=12.0.1=habf9029_0
  - libdeflate=1.8=h0d85af4_0
  - libedit=3.1.20191231=h0678c8f_2
  - libev=4.33=haf1e3a3_1
  - libffi=3.3=hb1e8313_2
  - libgfortran=5.0.0=9_3_0_h6c81a4c_23
  - libgfortran5=9.3.0=h6c81a4c_23
  - libglib=2.68.3=hd556434_0
  - libiconv=1.16=haf1e3a3_0
  - liblapack=3.9.0=10_openblas
  - liblapacke=3.9.0=10_openblas
  - libllvm10=10.0.1=h009f743_3
  - libllvm11=11.1.0=hd011deb_2
  - libnghttp2=1.43.0=h07e645a_0
  - libopenblas=0.3.17=openmp_h3351f45_1
  - libopencv=4.5.2=py39h852ad08_1
  - libpng=1.6.37=h7cec526_2
  - libpq=13.3=hea3049e_0
  - libprotobuf=3.16.0=hcf210ce_0
  - libsodium=1.0.18=hbcb3906_1
  - libssh2=1.9.0=h52ee1ee_6
  - libtiff=4.3.0=h1167814_0
  - libwebp-base=1.2.0=h0d85af4_2
  - libxml2=2.9.12=h93ec3fd_0
  - libzopfli=1.0.3=h046ec9c_0
  - llvm-openmp=12.0.1=hda6cdc1_1
  - llvmlite=0.36.0=py39h798a4f4_0
  - locket=0.2.0=py_2
  - lz4-c=1.9.3=he49afe7_1
  - markupsafe=2.0.1=py39h89e85a6_0
  - matplotlib=3.4.2=py39h6e9494a_0
  - matplotlib-base=3.4.2=py39hb07454d_0
  - matplotlib-inline=0.1.2=pyhd8ed1ab_2
  - mistune=0.8.4=py39h89e85a6_1004
  - mysql-common=8.0.25=h694c41f_2
  - mysql-libs=8.0.25=h115446f_2
  - nbclient=0.5.3=pyhd8ed1ab_0
  - nbconvert=6.1.0=py39h6e9494a_0
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.2=h0a44026_1
  - nd2reader=3.3.0=pyhd8ed1ab_0
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - nettle=3.6=hedd7734_0
  - networkx=2.3=py_0
  - notebook=6.4.0=pyha770c72_0
  - nspr=4.30=hcd9eead_0
  - nss=3.67=h31e2bf1_0
  - numba=0.53.1=py39h32e38f5_1
  - numpy=1.21.1=py39h7eed0ac_0
  - olefile=0.46=pyh9f0ad1d_1
  - opencv=4.5.2=py39h6e9494a_1
  - openh264=2.1.1=hfd3ada9_0
  - openjpeg=2.4.0=h6e7aa92_1
  - openssl=1.1.1k=h0d85af4_0
  - packaging=21.0=pyhd8ed1ab_0
  - pandoc=2.14.1=h0d85af4_0
  - pandocfilters=1.4.2=py_1
  - parso=0.8.2=pyhd8ed1ab_0
  - partd=1.2.0=pyhd8ed1ab_0
  - pcre=8.45=he49afe7_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.3.1=py39he9bb72f_0
  - pims=0.5=pyh9f0ad1d_1
  - pip=21.2.2=py39hecd8cb5_0
  - pixman=0.40.0=hbcb3906_0
  - pooch=1.4.0=pyhd8ed1ab_0
  - prometheus_client=0.11.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.19=pyha770c72_0
  - prompt_toolkit=3.0.19=hd8ed1ab_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - py-opencv=4.5.2=py39h71a6800_1
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.9.0=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py39h6e9494a_7
  - pyqt-impl=5.12.3=py39hef7122c_7
  - pyqt5-sip=4.19.18=py39hd8f94c5_7
  - pyqtchart=5.12=py39hef7122c_7
  - pyqtwebengine=5.12.1=py39hef7122c_7
  - pyrsistent=0.17.3=py39h89e85a6_2
  - pysocks=1.7.1=py39h6e9494a_3
  - python=3.9.6=h88f2d9e_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pywavelets=1.1.1=py39hae3b40e_3
  - pyyaml=5.4.1=py39hcbf5805_0
  - pyzmq=22.1.0=py39h7fec2f1_0
  - qt=5.12.9=h126340a_4
  - qtconsole=5.1.1=pyhd8ed1ab_0
  - qtpy=1.9.0=py_0
  - readline=8.1=h9ed2024_0
  - requests=2.26.0=pyhd8ed1ab_0
  - scikit-image=0.18.2=py39h4d6be9b_0
  - scipy=1.7.0=py39h056f1c0_1
  - send2trash=1.7.1=pyhd8ed1ab_0
  - setuptools=52.0.0=py39hecd8cb5_0
  - six=1.16.0=pyh6c4a22f_0
  - slicerator=1.0.0=py_0
  - snappy=1.1.8=hb1e8313_3
  - sqlite=3.36.0=hce871da_0
  - terminado=0.10.1=py39h6e9494a_0
  - testpath=0.5.0=pyhd8ed1ab_0
  - tifffile=2021.7.30=pyhd8ed1ab_0
  - tk=8.6.10=hb0a8c7a_0
  - toolz=0.11.1=py_0
  - tornado=6.1=py39h89e85a6_1
  - tqdm=4.62.0=pyhd8ed1ab_0
  - traitlets=5.0.5=py_0
  - tzdata=2021a=h52ac0ba_0
  - urllib3=1.26.6=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - widgetsnbextension=3.5.1=py39h6e9494a_4
  - x264=1!161.3030=h0d85af4_1
  - xmltodict=0.12.0=py_0
  - xz=5.2.5=h1de35cc_0
  - yaml=0.2.5=haf1e3a3_0
  - zeromq=4.3.4=h1c7c35f_0
  - zfp=0.5.5=he49afe7_5
  - zipp=3.5.0=pyhd8ed1ab_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.5.0=h582d3a0_0
